# Nome da Aplicação
spring.application.name=estevaoLanches

# =====================================================================
# CONFIGURAÇÃO DO POSTGRESQL (Via Variáveis de Ambiente)
# =====================================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =====================================================================
# CONFIGURAÇÃO DO JPA / HIBERNATE
# =====================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =====================================================================
# 🚀 LOGS E DEBUG DE SQL AVANÇADO
# =====================================================================
# Mostra o SQL bruto gerado pelo Hibernate
spring.jpa.show-sql=true

# Formata o SQL quebrando linhas no terminal para facilitar a leitura
spring.jpa.properties.hibernate.format_sql=true

# Inclui comentários explicando de qual método JPA veio a query
spring.jpa.properties.hibernate.use_sql_comments=true

# 🔥 O PULO DO GATO: Exibe os valores dos parâmetros substituídos nas interrogações (?) das queries
logging.level.org.hibernate.orm.results.bind=trace