# Nome da Aplicação
spring.application.name=estevaoLanches

# =====================================================================
# CONFIGURAÇÃO DO POSTGRESQL (Via Variáveis de Ambiente)
# =====================================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =====================================================================
# CONFIGURAÇÃO DO JPA / HIBERNATE
# =====================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =====================================================================
# CONFIGURAÇÃO DE SEGURANÇA
# =====================================================================
google.client.id=407408718192.apps.googleusercontent.com
api.security.token.secret=ChaveSecretaEstevaoLanches2026!

# =====================================================================
# SWAGGER / OPENAPI
# =====================================================================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs